<?php

namespace PatrikGrinsvall\XConsole\ServiceProviders;

use Illuminate\Container\Container;
use Illuminate\Support\ServiceProvider;
use PatrikGrinsvall\XConsole\Commands\CleanCommand;
use PatrikGrinsvall\XConsole\Commands\HelpCommand;
use PatrikGrinsvall\XConsole\Commands\InstallCommand;
use PatrikGrinsvall\XConsole\Commands\RecordCommand;
use PatrikGrinsvall\XConsole\Commands\SrvCommand;
use PatrikGrinsvall\XConsole\Processer\FileWatcher;

class XConsoleLaravelServiceProvider extends ServiceProvider
{
    use CreatesApplication;


    public function provides(): array
    {
        return [ FileWatcher::class ];
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        if ($this->app->runningInConsole()) {
            /*
             * WIP
                        Artisan::command('x:tag', function () {
                            ProcessRunner::make(function () {
                                $composerFilename = dirname(__FILE__) . DIRECTORY_SEPARATOR . '/../../composer.json';
                                $composerJson     = json_decode(file_get_contents($composerFilename), true);
                                if (array_key_exists('version', $composerJson)) {
                                    $version = '0.0.' . (int)Str::afterLast('.', $composerJson['version']) + 1;
                                }
                                File::copy($composerFilename, $composerFilename . date("his") . ".bak");
                                $data = json_encode($composerJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
                                file_put_contents($composerFilename, $data);
                            })->run();
                        });
            */
            $this->app->extend($abstract, $closure);
            $this->commands([ 'x:srv' => SrvCommand::class ]);
            $this->commands([ 'x:help' => HelpCommand::class ]);
            $this->commands([ 'x:clean' => CleanCommand::class ]);
            $this->commands([ 'x:install' => InstallCommand::class ]);
            $this->commands([ 'x:record' => RecordCommand::class ]);
            #$this->app->register(ProcessRunner::class);
            Container::getInstance()->singleton(FileWatcher::class);
            $this->registred = true;
        } else {
            logger('not running in con');
        }

    }
}