<?php

namespace PatrikGrinsvall\XConsole\Commands\Style;


use Symfony\Component\Console\Style\SymfonyStyle;
use Throwable;

class SymfonyInputOutputStyle extends SymfonyStyle
{
    /**
     * Ask a question and return the answer.
     */
    public function write(iterable|string $messages, bool $newline = false, int $type = self::OUTPUT_NORMAL)
    {
        parent::write($messages, $newline, $type); // TODO: Change the autogenerated stub
    }

    /**
     * @param ...$msg
     * @return void
     * @throws Throwable
     */
    public function line(...$msg)
    {
        $line = $this->beforeLine();
        foreach ($msg as $key => $m) {
            if (is_array($m)) $m = implode(' ', $m);
            $line .= $this->color($m);
        }
        parent::getOutput()->write($$line, true);
        if (count($msg) - 1 == $key) parent::getOutput()->write("\n");
    }

    public function beforeLine()
    {
        return $this->color('[') . $this->color(date('Y-m-d h:i:s')) . ' - uptime:';
    }
}